name: danielzeiter.com
favicon: null
layout_spectrum: 0.74524
typography_spectrum: 0.94373
title: Daniel Zeiter
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#213b8b'
    - '#d2d8e2'
    - '#3c7cbb'
    - '#72a1d3'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
