title: Dirigent · Saxophon
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 0.2234401
favicon: null
name: Daniel Zeiter
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.375
  lightness: 0.6231028
  saturation: 0.4932546
  rhythmicContrast: 0.6720067
  brandColors:
    - '#000000'
    - '#213b8b'
    - '#d2d8e2'
    - '#3c7cbb'
    - '#72a1d3'
typography_spectrum: 0.65739
