name: Daniel Zeiter
favicon: null
layout_spectrum: 1
typography_spectrum: 0.65739
title: Dirigent · Saxophon
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#213b8b'
    - '#d2d8e2'
    - '#3c7cbb'
    - '#72a1d3'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
