color:
  brandStrength: 1
  saturation: 0.25
  brandColors:
    - '#000000'
    - '#213b8b'
    - '#d2d8e2'
    - '#3c7cbb'
    - '#72a1d3'
  lightness: 0.25
  rhythmicContrast: 0.25
title: Daniel Zeiter
analytics:
  twitter: null
  google: null
  facebook: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
favicon: null
layout_spectrum: 0.50478
purpose: []
name: danielzeiter.com
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.94373
